FROM microsoft/windowsservercore

# RUN mkdir c:/test
# ENV DIR c:/test

COPY createAzureKeyVaultUsingARM.ps1 .
COPY pushJSONSecretsToKeyVault.ps1 .
COPY getSecrets.ps1 .
COPY runAll.ps1 .
COPY JSONFile .
COPY parameters.json .

# CMD ["c:\\test\\runAll.ps1"]
CMD powershell .\runAll.ps1