FROM microsoft/windowsservercore

RUN mkdir c:\test
ENV DIR c:\test

COPY createAzureKeyVaultUsingARM.ps1 $DIR
COPY pushJSONSecretsToKeyVault.ps1 $DIR
COPY getSecrets.ps1 $DIR
COPY runAll.ps1 $DIR
COPY JSONFile $DIR
COPY parameters.json $DIR

CMD ["c:\\test\\runAll.ps1"]